version: '3'
services:
  nginx:
   container_name: sbc-nginx
   image: nginx:1.13
   #   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app
 
  mysql:
   container_name: sbc-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
     #restart: always

# nginx需要通过app访问服务
  app:
    hostname: app
      #restart: always
    build: ./springboot-docker-compose
    working_dir: /app
    #  直接挂载项目目录，然后开发
    volumes:
      - ./springboot-docker-compose:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
        #      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
