server:
  port: 9411

zipkin:
  collector:
    rabbitmq:
      # 多个地址逗号分隔
      addresses: localhost:5672
      username: guest
      password: guest
      queue: zipkin
#  storage:
#    type: elasticsearch
#    elasticsearch:
#      cluster: elasticsearch
#      hosts: http://localhost:9200
#      index: zipkin
#      index-shards: 5
#      index-replicas: 1

spring:
  application:
    name: '@artifactId@'

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@${eureka.instance.hostname}:${eureka.instance.port}/eureka
  instance:
    hostname: localhost
    port: 10000
