server:
  port: 9411

spring:
  application:
    name: '@artifactId@'

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@${eureka.instance.hostname}:${eureka.instance.port}/eureka
  instance:
    hostname: localhost
    port: 10000
