eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@peer1:8761/eureka,http://user:password@peer2:8762/eureka #高可用配置
  instance:
    hostname: localhost
    port: 8761
    preferIpAddress: true # 将自己的ip注册到eureka server上, 没起作用

# 自定义白名单
security:
#  loginpage: http://${GATEWAY_SERVER:127.0.0.1}:${GATEWAY_SERVER_PORT:80}/busportal/login.page
  ignoring:
    antpatterns: '/demo/**,/swagger-ui.html,/api/**'

management:
  security:
    enabled: false

server:
  port: ${port:9090}
spring:
  application:
    name: '@artifactId@'
  # mq
  rabbitmq:
    host: 47.75.36.192
    port: 5672
    username: guest
    password: guest
  #zipkin
  zipkin:
    rabbitmq:
      queue: zipkin
#    # zipkin的地址：通过真实IP地址访问
##    base-url: http://${ZIPKIN_SERVER:127.0.0.1}:${ZIPKIN_SERVER_PORT:9411}
#    #通过服务名访问
#    base-url: http://zipkin-server/
#    enabled: true
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      #设置采样率，为了测试设置100%采集，设置为1.0
      percentage: 1.0  #zipkin采集率  0.1表示 10%采集率

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
