spring:
  application:
    name: springboot-liquibase
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: dev
  port: 8080

---
spring:
  profiles: dev
  liquibase:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/liquibase?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

