#security.basic.enabled = false

#management.security.enabled = false
logging:
  level:
    root: info

spring:
  thymeleaf:
    cache: false
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# 设置session 超时时间
server:
  servlet:
    session:
      timeout: 600

# 白名单设置
auth_whitelist: /,/home,/hello,/code/image,/login,/logout,/signOut
