eureka:
  client:
    serviceUrl:
#      defaultZone: http://user:password@peer1:8761/eureka,http://user:password@peer2:8762/eureka #高可用配置
      defaultZone: http://user:password@${eureka.instance.hostname}:${eureka.instance.port}/eureka
  instance:
    hostname: localhost
    port: 8761
    preferIpAddress: true
    # 自定义元数据
    metadataMap:
      my-metadata: hello
#management:
#  security:
#    enabled: false
server:
  port: ${port:7070}

spring:
  application:
    name: '@artifactId@'
  profiles:
    active: native #默认使用本地配置
  # 开启配置服务安全认证
  security:
    basic:
      enabled: true # 开启http basic认证
    user:
      name: user
      password: password
    admin:
      name: user
      password: password

# rabbitmq bus
rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
---

# 请求方式 http://127.0.0.1:7070/zuul/default
spring:
  profiles: git
  cloud:
    config:
      bus:
        trace:
          enabled: true
      server:
        git:
          basedir: /tmp/data #配置下载路径
          search-paths: '{application}'
          force-pull: true
          uri: https://github.com/p205/cloud-config-repo
          username: xxxx #账号密码写真实的快一些我觉得，不使用也能访问有点慢
          password: HxxxRnI

---

spring:
  profiles: native  # 配置使用本地储存
  cloud:
    config:
      server:
        native:
          # 访问http://host:port/zuul/dev 就会到xxx/zuul/目录下去找
          search-locations: ${CONFIGSPATH:${user.dir}/config-server/src/main/resources/configs}/{application}
      allowOverride: false
      overrideNone: false
      overrideSystemProperties: false

---

spring:
  profiles: subversion
  cloud:
    config:
      bus:
        trace:
          enabled: true
      server:
        svn:
          basedir: /tmp/data
          default-label:
          password: '{cipher}AICZ22ragF2cVLaYaPOXXMz2uCQ3e++5sLTRI6eokUi3HPAQE6+HjxeMvavBjwlnUcrH5t+Q/0IC7kwMnxqxHvdPENsziEl+cCfjXug+/5cjbmqcwYY+YbRwIzQIKBEliSPgfCEg23VbBzYNR0N/uDAAY2fmWlNHO/K6XMQ6aBUnc9AnIXIJ4Zo6ZZ6ZztqAa8b8ZyMMauklsHp0zegtYXZB'
          search-paths: '{application}'
          uri: http://host:port/cloud-config-repo
          username: xxx

#spring.application.name=@artifactId@
#server.port=${port:7070}
#management.security.enabled=false
#
## cloudserver 配置
#spring.cloud.config.server.git.uri=file://${user.dir}/config-server/src/main/resources/configs
## 一定注意， 如果不是github上获取配置，下面千万别打开，不然客户端这辈子取不到配置
#spring.cloud.config.server.git.force-pull=true
#
## 注册到eureka
#eureka.instance.hostname=localhost
#eureka.instance.port=8761
#eureka.client.serviceUrl.defaultZone=http://user:password@${eureka.instance.hostname}:${eureka.instance.port}/eureka
