eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@${eureka.instance.hostname}:${eureka.instance.port}/eureka
  instance:
    hostname: localhost
    port: 10000
    preferIpAddress: true # 将自己的ip注册到eureka server上, 没起作用
management:
  security:
    enabled: false
server:
  port: ${port:9001}
spring:
  application:
    name: '@artifactId@'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 中间件方式不需要appconfig配置
#turbine:
#  appConfig: user-service-provider
#  clusterNameExpression: "'default'"
