#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://user:password@peer1:8761/eureka,http://user:password@peer2:8762/eureka #高可用配置
#  instance:
#    hostname: localhost
#    port: 8761
#    preferIpAddress: true # 将自己的ip注册到eureka server上, 没起作用
management:
  security:
    enabled: false
server:
  port: ${port:9001}
spring:
  application:
    name: '@artifactId@'
  rabbitmq:
    host: ${RABBITMQ_SERVER:localhost}
    port: ${RABBITMQ_SERVER_PORT:5672}
    username: ${RABBITMQ_SERVER_USERNAME:guest}
    password: ${RABBITMQ_SERVER_PASSWORD:guest}

# 中间件方式不需要appconfig配置, 当然也就不再需要连eureka
#turbine:
#  appConfig: user-service-provider
#  clusterNameExpression: "'default'"
