spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/test3
    username: root
    # 建表语句
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    sql-script-encoding: utf-8
    #在SpringBoot1.x中, 运行schema.sql不需要配置便可之间运行,但是在SpringBoot2.x中,我们需要在配置文件中配置一下:
    initialization-mode: always
